name: Process and Append Data

on:
  workflow_dispatch:
    inputs:
      blob_url:
        description: 'The URL of the new data blob'
        required: true

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas azure-storage-blob numpy feature-engine requests openpyxl

    - name: Check if the blob URL contains estate_soe_combined_api_latest.xlsx
      id: check_filename
      run: |
        FILENAME=$(basename "${{ github.event.inputs.blob_url }}")
        if [[ "$FILENAME" == "estate_soe_combined_api_latest.xlsx" ]]; then
          echo "SKIP_WORKFLOW=true" >> $GITHUB_ENV
        else
          echo "SKIP_WORKFLOW=false" >> $GITHUB_ENV
        fi

    - name: Skip workflow if filename matches estate_soe_combined_api_latest.xlsx
      if: env.SKIP_WORKFLOW == 'true'
      run: |
        echo "The blob URL contains estate_soe_combined_api_latest.xlsx. Skipping workflow."

    - name: Download new data file
      if: env.SKIP_WORKFLOW == 'false'
      env:
        BLOB_URL: ${{ github.event.inputs.blob_url }}
      run: |
        wget -O new_datafile.xlsx "${{ env.BLOB_URL }}"

    - name: Run preprocessing script
      if: env.SKIP_WORKFLOW == 'false'
      env:
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: |
        python preprocess_and_append.py new_datafile.xlsx
